### PR TITLE
Fix missing dependencies in useEffect hook

### PR DESCRIPTION
**Pull request by Gri-ffin**
The problem wasn't with the workflows, but you when you used The useEffect hook you forgot to add dependencies to you hook which will let you app re-render on every useEffect call that doesn't have a array of dependencies which causes you app to enter an infinite loop.
Note that I also added the useMemo hook for better performance.

when the workflow run the script npm build react found that problem and threw an error.

This should fix workflows.

### CODE REVIEW

**Comment by Gri-ffin** [comment]
wait till the workflows run to merge this.

**Comment by Gri-ffin** [comment]
it seems that you have no tests written so I just removed npm test as it will throw an error

**Comment by Gri-ffin** [comment]
Well look at that, everything is ready, you can merge this.

that was a lot of work.

note: don't forget to add dependencies to you useEffect hook as that will make you react app enter an infinite loop which is bad :p

**Comment by Gri-ffin** [comment]
you can add later npm test when you write some test cases for you project if you want

**Comment by Code-Done-Right** [comment]
thanks!

**Pull request merged**
